const CATEGORY_NAMES={history:'Sejarah Indonesia',geography:'Geografi Indonesia',culture:'Budaya Nusantara',national_figure:'Tokoh Nasional',state:'Pancasila & Kenegaraan',nature:'Alam Indonesia',language:'Bahasa Indonesia',culinary:'Kuliner Nusantara',art:'Seni',sport:'Olahraga'};
const $=id=>document.getElementById(id);
const game={status:'setup',duration:15,matchRemaining:300,rope:0,timer:null,settings:null,questions:{left:[],right:[]},left:null,right:null,winner:null};
function team(name){return{name,score:0,combo:0,maxCombo:0,correct:0,wrong:0,totalTime:0,selected:null,answered:false,pull:0,round:0,finished:false,history:[]}}
function shuffle(items){const a=[...items];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pool(){const s=game.settings;return indonesiaQuestions.filter(q=>s.categories.includes(q.category)&&(s.difficulty==='mixed'||q.difficulty===+s.difficulty))}
function randomizeOptions(question){const choices=shuffle(question.options.map((text,index)=>({text,isCorrect:index===question.correctAnswer})));return{...question,options:choices.map(choice=>choice.text),correctAnswer:choices.findIndex(choice=>choice.isCorrect)}}
function questionsByDifficulty(items){return items.reduce((groups,question)=>{(groups[question.difficulty]??=[]).push(question);return groups},{})}
function buildQuestionOrder(items,difficultyOrder){const groups=questionsByDifficulty(items);const queues=Object.fromEntries(Object.entries(groups).map(([difficulty,questions])=>[difficulty,shuffle(questions)]));return difficultyOrder.map(difficulty=>queues[difficulty].pop()).map(randomizeOptions)}
function prepareQuestions(){const all=pool();if(game.settings.difficulty!=='mixed'){game.questions={left:shuffle(all).map(randomizeOptions),right:shuffle(all).map(randomizeOptions)};return}const difficultyOrder=shuffle(all.map(question=>question.difficulty));game.questions={left:buildQuestionOrder(all,difficultyOrder),right:buildQuestionOrder(all,difficultyOrder)}}
function pullPower(ok,remaining,combo,side){if(!ok)return 0;const used=1-remaining/game.duration;let value=10+(used<=.25?5:used<=.5?3:used<=.75?1:0)+(combo>=5?5:combo>=3?3:combo>=2?2:0);const losing=(side==='left'&&game.rope>65)||(side==='right'&&game.rope< -65);return Math.round(value*(losing?1.15:1))}
function renderTeam(side){const t=game[side];$(side+'Name').textContent=t.name;$(side+'Score').textContent=t.score;$(side+'Combo').textContent=`COMBO x${t.combo}`}
function setTimer(side,value){game[side].remaining=value;const el=$(side+'Timer');el.textContent=`00:${String(value).padStart(2,'0')}`;el.classList.toggle('urgent',value<=5&&!game[side].answered)}
function updateRoundLabel(){const minutes=Math.floor(game.matchRemaining/60),seconds=game.matchRemaining%60;$('roundLabel').textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;$('roundLabel').classList.toggle('urgent',game.matchRemaining<=30)}
function renderQuestion(side){const t=game[side],q=game.questions[side][t.round];t.answered=false;t.selected=null;$(side+'Meta').textContent=`${CATEGORY_NAMES[q.category]} / ${['','MUDAH','SEDANG','SULIT'][q.difficulty]}`;$(side+'Question').textContent=q.question;$(side+'Feedback').textContent='';$(side+'Feedback').className='feedback';const box=$(side+'Answers');box.replaceChildren(...q.options.map((text,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.innerHTML=`<span>${String.fromCharCode(65+i)}</span><b>${text}</b>`;b.onclick=()=>answer(side,i);return b}));setTimer(side,game.duration);renderTeam(side);updateRoundLabel()}
function startRound(){game.status='playing';game.roundStarted=performance.now();renderQuestion('left');renderQuestion('right');clearInterval(game.timer);game.timer=setInterval(tick,1000)}
function tick(){game.matchRemaining--;updateRoundLabel();if(game.matchRemaining<=0){finishByScore();return}for(const side of ['left','right']){const t=game[side];if(!t.answered&&!t.finished){setTimer(side,t.remaining-1);if(t.remaining<=0)answer(side,null)}}}
function answer(side,index){const t=game[side];if(game.status!=='playing'||t.answered||t.finished)return;t.answered=true;t.selected=index;const q=game.questions[side][t.round],ok=index===q.correctAnswer;t.combo=ok?t.combo+1:0;t.maxCombo=Math.max(t.maxCombo,t.combo);t[ok?'correct':'wrong']++;const elapsed=game.duration-t.remaining;t.totalTime+=elapsed;t.pull=pullPower(ok,t.remaining,t.combo,side);const points=ok?100+t.remaining*10+t.combo*10:0;t.score+=points;t.history.push({question:q.question,category:CATEGORY_NAMES[q.category],difficulty:q.difficulty,selectedAnswer:index===null?null:q.options[index],correctAnswer:q.options[q.correctAnswer],explanation:q.explanation,correct:ok,timeout:index===null,points,time:elapsed});const buttons=[...$(side+'Answers').children];buttons.forEach((b,i)=>{b.disabled=true;if(i===q.correctAnswer)b.classList.add('correct');if(i===index&&!ok)b.classList.add('wrong')});const feedback=$(side+'Feedback');feedback.textContent=ok?'BENAR':index===null?'WAKTU HABIS':'SALAH';feedback.className=`feedback ${ok?'good':'bad'}`;renderTeam(side);if(t.pull)applyPull(side,t.pull);setTimeout(()=>advanceTeam(side),450)}
function applyPull(side,amount){game.rope=Math.max(-100,Math.min(100,game.rope+(side==='left'?-amount:amount)));$('rope').style.setProperty('--position',`${game.rope*.38}%`);$('pullText').textContent=`${side==='left'?'KIRI':'KANAN'} +${amount}`;$('pullText').classList.add('show');setTimeout(()=>$('pullText').classList.remove('show'),500)}
function advanceTeam(side){if(game.status!=='playing')return;const t=game[side];t.round++;if(t.round>=game.questions[side].length){t.finished=true;$(side+'Question').textContent='Bank soal untuk pilihan ini sudah habis';$(side+'Meta').textContent='TIDAK ADA SOAL BERULANG';$(side+'Answers').replaceChildren();$(side+'Feedback').textContent='SELESAI';setTimer(side,0);return}renderQuestion(side)}
function finishByScore(){if(game.left.score===game.right.score){finishDraw();return}finish(game.left.score>game.right.score?'left':'right')}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function accuracy(t){return Math.round(t.correct/(t.correct+t.wrong)*100)||0}
function renderHistory(side){const t=game[side];const rows=t.history.length?t.history.map((entry,index)=>{const status=entry.correct?'BENAR':entry.timeout?'WAKTU HABIS':'SALAH';const reason=entry.correct?entry.explanation:`Jawaban yang benar adalah “${entry.correctAnswer}”. ${entry.explanation}`;return `<details class="history-item ${entry.correct?'is-correct':'is-wrong'}"><summary><span class="history-number">${index+1}</span><span class="history-question"><b>${escapeHtml(entry.question)}</b><small>${escapeHtml(entry.category)} · ${['','MUDAH','SEDANG','SULIT'][entry.difficulty]}</small></span><span class="history-status">${status}</span></summary><div class="history-detail"><p><b>Jawaban tim:</b> ${escapeHtml(entry.selectedAnswer??'Tidak menjawab')}</p><p><b>Jawaban benar:</b> ${escapeHtml(entry.correctAnswer)}</p><p><b>${entry.correct?'Mengapa benar':'Mengapa salah'}:</b> ${escapeHtml(reason)}</p><small>Waktu ${entry.time} detik · +${entry.points} poin</small></div></details>`}).join(''):'<p class="empty-history">Belum ada jawaban.</p>';return `<section class="team-history"><h3>${escapeHtml(t.name)}</h3>${rows}</section>`}
function renderResults(winnerSide=null){$('resultSubtitle').textContent=winnerSide?'PEMENANG TARIK MERDEKA':'HASIL AKHIR TARIK MERDEKA';$('stats').innerHTML=['left','right'].map(side=>{const t=game[side];return `<article class="team-result ${side===winnerSide?'is-winner':''}"><h2>${escapeHtml(t.name)}${side===winnerSide?'<small>PEMENANG</small>':''}</h2><div class="team-result-numbers"><span><b>${t.score}</b><small>SKOR</small></span><span><b>${t.correct}</b><small>BENAR</small></span><span><b>${t.wrong}</b><small>SALAH</small></span><span><b>${accuracy(t)}%</b><small>AKURASI</small></span></div></article>`}).join('');$('answerHistory').innerHTML=renderHistory('left')+renderHistory('right')}
function finishDraw(){if(game.status==='finished')return;clearInterval(game.timer);game.status='finished';game.winner=null;$('winnerName').textContent='PERTANDINGAN SERI';renderResults();$('victory').hidden=false}
function finish(side){if(game.status==='finished')return;clearInterval(game.timer);game.status='finished';game.winner=side;$('winnerName').textContent=game[side].name;renderResults(side);$('victory').hidden=false}
function begin(settings){game.settings=settings;game.duration=settings.duration;game.matchRemaining=settings.matchMinutes*60;game.rope=0;game.left=team(settings.leftName);game.right=team(settings.rightName);prepareQuestions();if(!game.questions.left.length){alert('Kombinasi kategori dan kesulitan tidak memiliki cukup soal.');$('setup').hidden=false;return}localStorage.setItem('tarikMerdekaSettings',JSON.stringify(settings));$('setup').hidden=true;$('victory').hidden=true;$('rope').style.setProperty('--position','0%');updateRoundLabel();countdown()}
function countdown(){game.status='countdown';$('countdown').hidden=false;const values=['3','2','1','MERDEKA!'];let i=0;const show=()=>{const el=$('countdownText');el.textContent=values[i];el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop');if(++i<values.length)setTimeout(show,700);else setTimeout(()=>{$('countdown').hidden=true;startRound()},750)};show()}
function readSettings(){return{leftName:$('leftInput').value.trim(),rightName:$('rightInput').value.trim(),matchMinutes:+$('matchTimeInput').value,duration:+$('timeInput').value,difficulty:$('difficultyInput').value,categories:[...document.querySelectorAll('[name=category]:checked')].map(x=>x.value)}}
function showSetup(){$('victory').hidden=true;$('setup').hidden=false;game.status='setup';clearInterval(game.timer)}
function init(){for(const [key,name] of Object.entries(CATEGORY_NAMES)){$('categoryInputs').insertAdjacentHTML('beforeend',`<label><input type="checkbox" name="category" value="${key}" checked><span>${name}</span></label>`)}const saved=JSON.parse(localStorage.getItem('tarikMerdekaSettings')||'null');if(saved){$('leftInput').value=saved.leftName;$('rightInput').value=saved.rightName;$('matchTimeInput').value=saved.matchMinutes||5;$('timeInput').value=saved.duration;$('difficultyInput').value=saved.difficulty} $('setupForm').onsubmit=e=>{e.preventDefault();const s=readSettings();if(!s.categories.length)return alert('Pilih minimal satu kategori.');begin(s)};$('settingsButton').onclick=showSetup;$('newMatch').onclick=showSetup;$('rematch').onclick=()=>begin(game.settings);document.addEventListener('keydown',e=>{const left='1234'.indexOf(e.key),right='7890'.indexOf(e.key);if(left>=0)answer('left',left);if(right>=0)answer('right',right)})}init();
